runtime: nodejs18
env: standard
instance_class: F1  # Adjust based on your application needs

readiness_check:
  path: "/health"  # Ensure this matches your health check endpoint

handlers:
  - url: /.*
    script: auto
